[openai]
api_key = ""
model = "gpt-5-nano"
rpm = 220
concurrency = 20

[hume_ai]
api_key = ""
model = "octave"
voice_name = "ivan"
octave_version = "2"
audio_format = "mp3"
split_utterances = true
rpm = 75
concurrency = 4
pricing_free_chars = 140000
pricing_rate_per_1k = 0.15

[elevenlabs]
api_key = ""
model = "eleven_v3"
voice_name = "VOICE_ID"
audio_format = "mp3"
rpm = 60
concurrency = 4
max_chars_limit = 5000 # 5k eleven_v3 and 40k for eleven_multilingual_v2
pricing_free_chars = 0
pricing_rate_per_1k = 0.30 # eleven_v3 and eleven_multilingual_v2

[retry]
attempts = 4
backoff_base = 0.5
backoff_max = 8
jitter = true

[translate]
input_file = "project.strings.xml"
output_file = "project/values/strings.xml"
progress_file = ".cache/project_progress.json"
allowed_regex = "^chp10_"
ignore_regex = ""
dry_run = false
stop_after = 0
count_tokens_enabled = true
target_language = "Russian"
provider = "openai"

[voice]
input_file = ".cache/project_progress.json"
output_dir = "project/voice"
allowed_regex = "^chp"
ignore_regex = ""
stop_after = 0
target_language = "Russian"
provider = "hume_ai"
max_elapsed_seconds = 600
dry_run = false
